language: ruby
addons:
  postgresql: "9.3"
rvm:
  - '2.1.2'
before_install:
  - sudo apt-get install -qq phantomjs
before_script:
  - cp .env.sample .env
  - bundle exec rake db:test:prepare
notifications:
  email: false
